/** @type {import('tailwindcss').Config} */
module.exports = {
  // Kde má Tailwind hledat použité třídy
  content: [
    "./*.html",
    "./**/*.html",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#4f5a40",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#b5d17b",
        "inverse-on-surface": "#f3f0f0",
        background: "#fbf9f8",
        secondary: "#4f661d",
        "surface-variant": "#e4e2e1",
        "on-primary-container": "#c4d1b0",
        "inverse-surface": "#303030",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#536a21",
        "surface-dim": "#dcd9d9",
        outline: "#76786f",
        error: "#ba1a1a",
        "outline-variant": "#c6c7bc",
        "on-tertiary-container": "#cecbcb",
        "surface-container": "#f0eded",
        "on-surface-variant": "#45483f",
        "on-surface": "#1b1c1c",
        "on-background": "#1b1c1c",
        "surface-container-low": "#f6f3f2",
        "surface-container-highest": "#e4e2e1",
        "primary-fixed-dim": "#bfcbab",
        "surface-tint": "#576248",
        "secondary-container": "#ceea92",
        "on-primary": "#ffffff",
        primary: "#38432a",
        "on-secondary": "#ffffff",
        "tertiary-container": "#575656",
        tertiary: "#3f3f3f",
        "inverse-primary": "#bfcbab",
        "surface-bright": "#fbf9f8",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        surface: "#fbf9f8",
        "primary-fixed": "#dbe7c5",
        "secondary-fixed": "#d1ed94",
        "surface-container-high": "#eae7e7",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
